name: Docker Build

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

env:
  GITHUB_ACTOR: ${{ github.actor }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CI: true

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USR }}
          password: ${{ secrets.DOCKER_PSW }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: frogdevelopment/eclipse-temurin-jre-17-curl:17.0.4.1_1-jre-alpine
